In [1]:
import pandas as pd

In [4]:
dt=pd.read_csv("bank.csv")
dt

     Bank   DD  Withdrawals  Deposits  Branch Area in sqft  avg daily walkins
0       1  227          147       111                 2460                639
1       2  123           86        65                 3510                436
2       3  306          149        76                 2570                669
3       4  251          112       129                 3650                623
4       5  174          135       128                 3400                579
..    ...  ...          ...       ...                  ...                ...
510   511  337          140       111                 2640                694
511   512  168          131        60                 2640                524
512   513  333           86       108                 2850                676
513   514  192          176        34                 2760                505
514   515  331          186        97                 2700                767

[515 rows x 6 columns]

In [5]:
dt.isnull().sum()

Bank                   0
DD                     0
Withdrawals            0
Deposits               0
Branch Area in sqft    0
avg daily walkins      0
dtype: int64

In [6]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Bank                 515 non-null    int64
 1   DD                   515 non-null    int64
 2   Withdrawals          515 non-null    int64
 3   Deposits             515 non-null    int64
 4   Branch Area in sqft  515 non-null    int64
 5   avg daily walkins    515 non-null    int64
dtypes: int64(6)
memory usage: 24.3 KB

In [8]:
dt.describe()

,Bank,DD,Withdrawals,Deposits,Branch Area in sqft,avg daily walkins
count,515.000000,515.000000,515.000000,515.000000,515.000000,515.000000
mean,258.000000,232.252427,150.693204,81.687379,2934.669903,598.603883
std,148.811962,66.648815,56.897777,28.596912,437.062831,83.487891
min,1.000000,120.000000,10.000000,33.000000,1200.000000,380.000000
25%,129.500000,169.500000,103.000000,58.000000,2675.000000,537.500000
50%,258.000000,237.000000,152.000000,80.000000,2960.000000,601.000000
75%,386.500000,291.000000,200.000000,105.000000,3300.000000,657.500000
max,515.000000,350.000000,247.000000,212.000000,3650.000000,838.000000

In [9]:
num=dt.select_dtypes(include=["int64","float64"])
num

     Bank   DD  Withdrawals  Deposits  Branch Area in sqft  avg daily walkins
0       1  227          147       111                 2460                639
1       2  123           86        65                 3510                436
2       3  306          149        76                 2570                669
3       4  251          112       129                 3650                623
4       5  174          135       128                 3400                579
..    ...  ...          ...       ...                  ...                ...
510   511  337          140       111                 2640                694
511   512  168          131        60                 2640                524
512   513  333           86       108                 2850                676
513   514  192          176        34                 2760                505
514   515  331          186        97                 2700                767

[515 rows x 6 columns]

In [11]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler=StandardScaler()
snumb=scaler.fit_transform(num)
snumb

array([[-1.72869086, -0.07888413, -0.06497257,  1.02602411, -1.08710095,
         0.48432644],
       [-1.72196444, -1.64081915, -1.13811308, -0.58410514,  1.31763546,
        -1.949528  ],
       [-1.71523801,  1.10758573, -0.02978763, -0.19907423, -0.83517619,
         0.84400936],
       ...,
       [ 1.71523801,  1.51308809, -1.13811308,  0.92101568, -0.19391314,
         0.92793538],
       [ 1.72196444, -0.60453534,  0.44520899, -1.66919225, -0.40003341,
        -1.12225728],
       [ 1.72869086,  1.48305088,  0.62113366,  0.53598477, -0.53744692,
         2.01897357]])

In [14]:
from sklearn.cluster import AgglomerativeClustering

In [16]:
model=AgglomerativeClustering(n_clusters=3,linkage="ward")
clusters=model.fit(snumb)
dt["cluster"]=clusters

In [ ]:
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram,linkage
plt.figure(figsize=(12,6))
dendrogram(linkage(snumb,method="ward"))
plt.title("dendrogram plot of dataset")
plt.xlabel("clustering")
plt.ylabel("depth")
plt.show()